<?php

declare(strict_types=1);

namespace MediTrack\Repositories;

use PDO;

final class DistributionScheduleRepository
{
    public function __construct(private readonly PDO $db)
    {
    }

    public function create(int $medicineId, string $scheduledDate, string $timeSlot, string $venue, bool $autoGenerated = true): int
    {
        $stmt = $this->db->prepare(
            'INSERT INTO distribution_schedules (medicine_id, scheduled_date, time_slot, venue, status, auto_generated)
             VALUES (:medicine_id, :scheduled_date, :time_slot, :venue, "upcoming", :auto_generated)'
        );
        $stmt->execute([
            'medicine_id' => $medicineId,
            'scheduled_date' => $scheduledDate,
            'time_slot' => $timeSlot,
            'venue' => $venue,
            'auto_generated' => $autoGenerated ? 1 : 0,
        ]);
        return (int) $this->db->lastInsertId();
    }

    public function find(int $id): ?array
    {
        $stmt = $this->db->prepare(
            'SELECT ds.*, m.name AS medicine_name FROM distribution_schedules ds
             JOIN medicines m ON m.id = ds.medicine_id WHERE ds.id = :id'
        );
        $stmt->execute(['id' => $id]);
        $row = $stmt->fetch();
        return $row ?: null;
    }

    /**
     * @param array{status?:string,medicine_id?:string,date_from?:string,date_to?:string} $filters
     * @return array{items:list<array<string,mixed>>,total:int}
     */
    public function paginate(array $filters, int $limit, int $offset): array
    {
        $where = ['1=1'];
        $params = [];

        if (!empty($filters['status'])) {
            $where[] = 'ds.status = :status';
            $params['status'] = $filters['status'];
        }
        if (!empty($filters['medicine_id'])) {
            $where[] = 'ds.medicine_id = :medicine_id';
            $params['medicine_id'] = $filters['medicine_id'];
        }
        if (!empty($filters['date_from'])) {
            $where[] = 'ds.scheduled_date >= :date_from';
            $params['date_from'] = $filters['date_from'];
        }
        if (!empty($filters['date_to'])) {
            $where[] = 'ds.scheduled_date <= :date_to';
            $params['date_to'] = $filters['date_to'];
        }

        $whereSql = 'WHERE ' . implode(' AND ', $where);

        $countStmt = $this->db->prepare("SELECT COUNT(*) FROM distribution_schedules ds {$whereSql}");
        $countStmt->execute($params);
        $total = (int) $countStmt->fetchColumn();

        $stmt = $this->db->prepare(
            "SELECT ds.id, ds.medicine_id, m.name AS medicine_name, ds.scheduled_date, ds.time_slot,
                    ds.venue, ds.status, ds.auto_generated
             FROM distribution_schedules ds
             JOIN medicines m ON m.id = ds.medicine_id
             {$whereSql}
             ORDER BY ds.scheduled_date DESC
             LIMIT :limit OFFSET :offset"
        );
        foreach ($params as $key => $value) {
            $stmt->bindValue($key, $value);
        }
        $stmt->bindValue('limit', $limit, PDO::PARAM_INT);
        $stmt->bindValue('offset', $offset, PDO::PARAM_INT);
        $stmt->execute();

        return ['items' => $stmt->fetchAll(), 'total' => $total];
    }

    /** @param array<string,mixed> $data */
    public function update(int $id, array $data): void
    {
        $stmt = $this->db->prepare(
            'UPDATE distribution_schedules SET scheduled_date = :scheduled_date, time_slot = :time_slot,
                venue = :venue, status = :status WHERE id = :id'
        );
        $stmt->execute([
            'scheduled_date' => $data['scheduled_date'],
            'time_slot' => $data['time_slot'],
            'venue' => $data['venue'],
            'status' => $data['status'],
            'id' => $id,
        ]);
    }
}
